### ISSUE TITLE
[NIRC] Create basic colony management forms on NIRC (Iteration 0)

### ISSUE THREAD

**Issue by wendyinnis** [LabKey/nircEHRModules#229]
### Tasks 📍

- [x] Team meeting @labkey-martyp @wendyinnis @jryurkanin 
- [x] setup NIRC test suite @labkey-bpatel 
- [x] create forms 
   - [x] Departure
   - [x] Arrival
   - [x] Death/Necropsy - initial form
   - [x] Update Animal Details section
   - [x] Housing
   - [x] Birth 
   - [x] Protocol Assignments
   - [x] Project Assignments
   - [x] Feedback updates
   - [x] Death/Necropsy - id propagation, 'Submit' buttons update, weight
   - [x] Death/Necropsy - update 'Gross Pathology' with pre-populated rows
   - [x] Fix test failure
- [x] setup and deploy to staging server @labkey-bpatel @labkey-jony
- [x] Code review @labkey-martyp 📍
- [x] Code review changes & client feedback updates @labkey-bpatel 📍
- [x] TC verify and merge
