### ISSUE TITLE
[NIRC] Death and Necropsy spec

### ISSUE THREAD

**Issue by wendyinnis** [LabKey/nircEHRModules#232]
[External Spec for Client Share](https://docs.google.com/document/d/1tTcOnckQ2WC-r7-mxFmAaB2cdl1QjEHw2qIKz8eqxT0/edit)
[Internal Spec](https://docs.google.com/document/d/19H3CPm4X_SxR6ipxNOnRT1XDFIy8PBMF-i5nKcSJCIQ/edit)
[epic link](https://github.com/LabKey/nircEHRModules/issues/236)
### Tasks 📍

- [x] Start spec @wendyinnis  4hrs 
- [x] Review external spec with client @labkey-bpatel @jryurkanin 
- [ ] Revise external spec  📍
- [ ] Implementation plan
- [ ] Dev Review
