### ISSUE TITLE
[NIRC] Birth Form -spec 

### ISSUE THREAD

**Issue by wendyinnis** [LabKey/nircEHRModules#233]
[External Client spec](https://docs.google.com/document/d/1wTsuK_qvuBFV-2bs4wEEDGILlFafE28Xxm4r55MV7OU/edit)
[Epic link](https://github.com/LabKey/nircEHRModules/issues/236)

### Tasks 📍

- [x] Start spec 📍 2 hrs
- [x] Review external spec @labkey-bpatel 
- [x] Review external spec with Client
- [ ] Revise spec 📍
