### ISSUE TITLE
[NIRC] Arrival form - spec

### ISSUE THREAD

**Issue by wendyinnis** [LabKey/nircEHRModules#237]
[spec](https://docs.google.com/document/d/1z9i_-wudzPzjdt8Z_H6GXaGIsq7ApDA045tuodTzOKk/edit) 
[epic link ](https://github.com/LabKey/nircEHRModules/issues/236)
### Tasks

- [x] Start spec 2 hrs 
- [x] Review external spec with Client
- [x] Review spec @labkey-bpatel 
- [x] Revise spec 📍
