### ISSUE TITLE
[NIRC] Basic colony management -Dev (Iteration 1)

### ISSUE THREAD

**Issue by wendyinnis** [LabKey/nircEHRModules#243]
[Basic Colony Management Epic]
(https://github.com/LabKey/nircEHRModules/issues/236)
[Arrival Form spec](https://docs.google.com/document/d/1z9i_-wudzPzjdt8Z_H6GXaGIsq7ApDA045tuodTzOKk/edit) 
[Brith form spec](https://docs.google.com/document/d/1wTsuK_qvuBFV-2bs4wEEDGILlFafE28Xxm4r55MV7OU/edit)
[Death & Necropsy spec ](https://docs.google.com/document/d/1tTcOnckQ2WC-r7-mxFmAaB2cdl1QjEHw2qIKz8eqxT0/edit)
[Departure Form spec](https://docs.google.com/document/d/1eLKDwt3OjSmRa08zsGc_DhzkfBtp6Ij07fSTsv8AfYA/edit)
[Housing Transfer spec](https://docs.google.com/document/d/1f-EUSW6NgGXxP7VFV6ZkDpznAnIx7AN97lREPDaBl0M/edit)

### Tasks

- [ ] add tasks @labkey-bpatel 
- [ ] Verify with client @labkey-bpatel 
- [ ] Code review 
- [ ] TC Verify and merge @labkey-bpatel
