### ISSUE TITLE
[NIRC] Project/Protocol Mgmt  User Feedback

### ISSUE THREAD

**Issue by labkey-bpatel** [LabKey/nircEHRModules#248]
### Tasks
- [x] Hide project and protocol assignment end dates. Extra testing to ensure automatically closing these. @ankurjuneja 
- [x] Combine initial project and protocol into arrival/birth data entry grids @ankurjuneja 
- [x] Update snapshot in all places it is used to include current project and protocol assignments and respective investigator last name @ankurjuneja 
- [x] Arrival/birth form should allow any Id, but all other forms should validate Ids @ankurjuneja 
- [x] All Ids will be auto upper cased @ankurjuneja 
- [x] Add Copy From Section menu option to all grids where it’s appropriate. @ankurjuneja 
- [x] Fix Bulk Add for protocols @ankurjuneja 
- [x] Add Series of IDs should only be on birth data entry grid @ankurjuneja 
- [x] Test update
- [x] Code Review
- [x] Code Review changes
- [x] Verify on TC and merge
