### ISSUE TITLE
[NIRC] Death/Necropsy workflow updates, plus Notes, Exemptions, and Flags data entry forms.

### ISSUE THREAD

**Issue by labkey-bpatel** [LabKey/nircEHRModules#249]
### Tasks
- [x] Remove weight section, and add as a single entry in Necropsy section 
- [x] Gross Pathology section - remove 'Add' btn
- [x] Prepopulate Gross Pathology section
- [x] Add 'Submit Death' button
- [x] Add Death notification 
- [x] Handle Death notification upon clicking 'Submit Death'
- [x] Trigger script updates
- [x] Demographics updates
- [x] Update Submit to only allow Alive animals at the center
- [x] Iterate with client on Death notification format
- [x] Update death notification format from client feedback 
- [x] Notes, Exemptions, Flags data entry forms - iteration 0 for requirements gathering
- [x] Weight updates
- [x] Re-label/re-do 'Submit for Review' button
- [x] Handle Permissions on the Submit buttons
- [x] Add lookups to Notes, Exemptions, Flags data entry forms
- [x] Test updates
- [x] Open PR 
- [x] Code Review @labkey-martyp 
- [x] Code Review changes
- [x] TC verify and merge
