### ISSUE TITLE
[NIRC] Add file repository

### ISSUE THREAD

**Issue by labkey-bpatel** [LabKey/nircEHRModules#250]
### Tasks
- [x] Update Animal History reporting to include file repository
- [x] Configure file repo (see JHU for example)
- [x] move file repository reporting to shared ehrModules
- [x] Code Review
- [x] Code Review changes
- [x] Test update?
- [x] TC verify and Merge

**Comment by jryurkanin** [comment]
@labkey-bpatel @ankurjuneja Let's start this after we iterate on the clinical forms again post feedback collection on 6/10
