### ISSUE TITLE
[NIRC Client Share] - Weights, aliases, pregnancy outcomes, and protocols/projects Forms Iteration 0

### ISSUE THREAD

**Issue by ankurjuneja** [LabKey/nircEHRModules#252]
### Tasks
- [x] nirc setup
- [x] Weights data entry form
- [x] New alias dataset
- [x] Alias data entry form
- [x] Pregnancy outcome data entry form
- [x] Protocol and project assignment data entry form
- [x] Feature verification @jryurkanin 
- [x] Code review @labkey-martyp 
- [x] TC review and merge
