### ISSUE TITLE
[NIRC] Protocol and Project Snapshot Values

### ISSUE THREAD

**Issue by labkey-martyp** [LabKey/nircEHRModules#288]
### Tasks
- [x] Project demographic provider
- [x] Protocol demographic provider
- [x] Feature Verification 📌 
- [x] Code Review
- [x] TC and Merge
