### ISSUE TITLE
[NIRC] Birth/Arrival Form Auto Test

### ISSUE THREAD

**Issue by labkey-martyp** [LabKey/nircEHRModules#289]
### Tasks
- [x] Test case for Arrival and Birth
    - [x] Enter Location 
    - [x] Enter Protocol
    - [x] Enter Project
- [x] Validate arrival, birth, housing and assignments
- [x] Fix Issues, update Birth form, other misc. things @labkey-bpatel 
- [x] Code Review @labkey-bpatel 
- [x] TC and Merge
