### ISSUE TITLE
[NIRC] Basic colony management - Death form updates

### ISSUE THREAD

**Issue by labkey-bpatel** [LabKey/nircEHRModules#307]
### Tasks
- [x] Filter 'Submit for Review' drop down to filter on Vets
- [x] Error handling/interim QC State
- [x] 'Performed By' values - data entry workflow
- [x] Allow past dates and allow time component
- [x] Navigation for Vets to get to Death/Necropsy form
- [x] Fix broken lookups for 'performed by' in various reports
- [x] Code review @labkey-martyp @ankurjuneja 
- [x] Code review changes
- [x] Test fixes
- [x] TC verify and merge

**Comment by jryurkanin** [comment]
@labkey-bpatel can you please confirm that this was all complete?
