### ISSUE TITLE
[NIRC] Clinical Form - Medications/Treatments

### ISSUE THREAD

**Issue by ankurjuneja** [LabKey/nircEHRModules#308]
### Tasks
- [x] Update drug dataset to add relevant columns 
- [x] Update study.treatment_order dataset to add relevant columns
- [x] Add lookups & lookups data for columns (in specs)
- [x] Add Medications/Treatments data entry form 📌 
- [x] Ensure that Amounts can be calculated based on Vol
- [x] Code review
- [x] Verify TC & merge
