### ISSUE TITLE
[NIRC] Clinical - Cases spec and iteration 1

### ISSUE THREAD

**Issue by labkey-robert** [LabKey/nircEHRModules#319]
### Tasks
- [x] [Open/Close Cases Functional Spec](https://docs.google.com/document/d/1G6yNOEpRuc3sbbzZlmWPcmB3VJ-wNIE7IOQihPBDgDk/edit) @labkey-bpatel  
- [ ] Add case management data entry - iteration 0 for client feedback
    - [x] Update ETLs
    - [x] Update cases dataset
    - [x] Add caseids to relevant datasets
    - [x] Lookups
    - [x] Add form sections for case relevant datasets
    - [x] Handle Case form section
    - [x] Open PR
    - [x] Code Review @ankurjuneja
    - [x] Code Review changes @labkey-bpatel 
    - [x] Code Review changes
    - [x] Merge PR
