### ISSUE TITLE
[NIRC] Orchard LIS Animal Data Integration

### ISSUE THREAD

**Issue by labkey-martyp** [LabKey/nircEHRModules#327]
[Spec](https://docs.google.com/document/d/1O0zCKicpj5koXPz6UGVSi_tlQsaJHfiMmT46xftGVio/edit)

### Tasks
- [x] Functional Spec @labkey-martyp 
- [x] Impl Plan and Tasks
- [x] Create new module property 
- [x] Create a query for the orchard data 
- [x] Create a Java class for the content creation containing a method for generating the content  
- [x] Create a java trigger helper
- [x] Modify demographics, protocol/project assignment and housing trigger scripts
- [x] Feature verification
- [x] code review 📌
