### ISSUE TITLE
[NIRC] Clinical Form - Cases Iteration 2 Spec and Planning

### ISSUE THREAD

**Issue by labkey-bpatel** [LabKey/nircEHRModules#333]
Release 24.3
[Iteration 2 Spec](https://docs.google.com/document/d/1NQcW1AUB--RkWdLhbxAPbO90sQpyhy6XuJrfDFVgKE8/edit)

### Tasks
- [x] Create spec, add Requirements
- [x] Functional design
- [x] Divide into small stories, add tasks for each
- [x] Review spec @labkey-martyp @jryurkanin
