### ISSUE TITLE
[NIRC] Clinical Form - Cases form updates

### ISSUE THREAD

**Issue by labkey-bpatel** [LabKey/nircEHRModules#336]
Implementation on release23.4
Spec [here](https://docs.google.com/document/d/1NQcW1AUB--RkWdLhbxAPbO90sQpyhy6XuJrfDFVgKE8/edit#heading=h.xjofbrptfqin).

### Tasks
- [x] Add Vitals, Clinical Obs, Procedures, Blood Draw sections
- [x] Add Clinical Remark section and related updates
- [x] Clinical Remark section -  Fix Id propagation 
- [x] Updates to Medication/Treatment Orders
- [x] Updates to Medication/Treatments Given
- [x] Handle form Permissions on case open/close
- [x] Fix bugs
- [x] Add test plan for Clinical Case
- [x] Add 'Active Clinical Case' report and a a navigation link to the main page
- [x] Sanity test the workflow and open PR
- [x] Code Review @ankurjuneja @labkey-martyp 
- [x] Code Review Changes
- [x] Code Review 2 @ankurjuneja @labkey-martyp 
- [x] Update Procedure lookup
- [x] TC Verify and merge
