### ISSUE TITLE
[NIRC] Clinical Case Workflow - Clinical Observations, Clinical Remarks and Animal Details

### ISSUE THREAD

**Issue by labkey-bpatel** [LabKey/nircEHRModules#337]
Implementation on 24.7 release
Spec [here](https://docs.google.com/document/d/1NQcW1AUB--RkWdLhbxAPbO90sQpyhy6XuJrfDFVgKE8/edit#heading=h.2eizh6mlq8ko).

### Tasks
- [x] Update 'obs' ETL
- [x] Add lookups for 'category'
- [x] Handle clinical obs for all open cases per animal
- [x] Add lookups for 'observations' and conditionalize
- [x] Allow case selection on Cases data entry
- [x] Support SOAP for clinremarks
- [x] Update existing cases/get ready for client demo @labkey-martyp
- [x] Client requested updates - SOAP
- [x] Client requested updates - cases view
- [x] Fix project display for Assignment views
- [x] Fix links in Animal Details
- [x] Add test plan
- [x] Bug fixes, cleanup, etc.
- [x] Code Review @labkey-martyp 
- [x] TC Verify and merge 📌
