### ISSUE TITLE
[NIRC] Clinical Form - Cases Reporting

### ISSUE THREAD

**Issue by labkey-bpatel** [LabKey/nircEHRModules#338]
Implementation on release23.4
Spec [here](https://docs.google.com/document/d/1NQcW1AUB--RkWdLhbxAPbO90sQpyhy6XuJrfDFVgKE8/edit#heading=h.dlavl3p3fcgq).

### Tasks
- [ ] Add 'Active Clinical Cases' report
- [ ] Add daily report 'Review Open Cases' report
- [ ] Add daily report 'Medication/Treatment Schedule'
- [ ] Add lookups where necessary (Ex. Procedure)
- [ ] Add test plan
- [ ] Code Review
- [ ] Code Review Changes
- [ ] TC Verify and merge
