### ISSUE TITLE
[NIRC] Basic Colony Data Entry - Client requested updates

### ISSUE THREAD

**Issue by labkey-bpatel** [LabKey/nircEHRModules#345]
Implementation on release23.4

### Tasks
Client requested updates on Basic Colony Mgmt forms
- [x] Arrival
- [x] Birth
- [x] Exemptions
- [x] Housing Transfer
- [x] Notes
- [x] Death/Necropsy
- [x] Updates to Project data entry
- [x] Regression fixes
- [x] Code Review @labkey-martyp 
- [x] Code Review Changes
- [x] Additional Client requested updates on Arrivals, Notes, Project, and couple minor issues
- [x] Test fixes
- [x] Verify code review updates @labkey-martyp 
- [x] TC Verify and merge
