### ISSUE TITLE
[NIRC] Basic Colony Data Entry - Client requested updates 2

### ISSUE THREAD

**Issue by labkey-bpatel** [LabKey/nircEHRModules#355]
Implementation on release23.4

### Tasks
Client requested updates on Basic Colony Mgmt forms
- [x] Death/Necropsy - Upon Submit Death, assign Tasks to Vet group
- [x] Code review @labkey-jeckels
- [x] TC review and merge
