### ISSUE TITLE
[NIRC] Colony Management User feedback - Death/Necropsy

### ISSUE THREAD

**Issue by labkey-bpatel** [LabKey/nircEHRModules#419]
### Tasks 📍

- [x] Fix 'Save Draft' issue
- [x] Update  Demographics status to 'Necropsy Pending' upon 'Submit Death'
- [x] Code review 
- [x] Feature Verification 📌 @labkey-martyp 
- [ ] TC Verify and merge
