### ISSUE TITLE
[NIRC] Behavioral Cases

### ISSUE THREAD

**Issue by labkey-martyp** [LabKey/nircEHRModules#422]
[Spec](https://docs.google.com/document/d/1ik1Qjb-R8lsgOcdYQhEc5YHxEKHNDFZjyplA1Uquxfs/edit?tab=t.0)

### Tasks 📍
- [x] Behavior Cases Form
- [x] Case Form Section
- [x] Remarks Form Section
- [x] Load Case From URL 
- [x] Active and Historical Behavior Case Reports
- [x] Edit Case Link
- [x] Select Open or Closed Case
- [x] Observations and observation orders 
- [x] Treatments and treatment orders
- [x] Feature Verification 
- [x] Code Review @labkey-bpatel 📌
- [x] TC and Merge
