### ISSUE TITLE
[NIRC] Behavior Cases User Feedback

### ISSUE THREAD

**Issue by labkey-martyp** [LabKey/nircEHRModules#432]
[Spec](https://docs.google.com/document/d/1CguWG7DGi2f9xW5AotVj9j70vsDqlXC9Ndf56uXwR6Y/edit?tab=t.0)
 
### Tasks 📍
- [x] Behavior Medications Schedule
- [x] Behavior Observation Schedule
- [x] Update Alopecia Observations
- [x] Update Wound Observations
- [x] Wound Observation Validation
- [x] Animal Detail/Snapshot
- [x] Weekly Frequency
- [x] Rename Clinical Observations form
- [x] Close observation orders when case closed
- [x] Don't open clinical obs on behavior case
- [x] Separate Clinical and Behavioral Active Observation Orders
- [x] End Observation orders should have date/time 
- [x] Require behaviorist Ordered by for behavior obs orders
- [x] Code Review
- [x] TC and merge
