### ISSUE TITLE
[NIRC] Behavior Cases - Testing

### ISSUE THREAD

**Issue by labkey-martyp** [LabKey/nircEHRModules#433]
[Spec](https://docs.google.com/document/d/1CguWG7DGi2f9xW5AotVj9j70vsDqlXC9Ndf56uXwR6Y/edit?tab=t.0)
### Tasks 📍 
- [x] Test plan @labkey-martyp 
- [x] Tasks
- [x] Create multiple behavior cases with observations, observation orders, medications given and medication orders
- [x] Verify reports and schedule 
- [x] Verify Close case 
- [x] Add IDs to fields @labkey-martyp 
- [x] update the tests 
- [x] Code review @labkey-martyp 📌
- [x] TC Verify and merge
