### ISSUE TITLE
[NIRC] Procedure Orders

### ISSUE THREAD

**Issue by labkey-martyp** [LabKey/nircEHRModules#455]
[Spec](https://docs.google.com/document/d/1_MeGElKgxCDJ4oqFCejx3VQipVAY-21BKCRC0cDlmMQ/edit?tab=t.0)
[Epic](https://github.com/orgs/LabKey/projects/5/views/2?filterQuery=NIRC&pane=issue&itemId=93907551&issue=LabKey%7CnircEHRModules%7C468)

## Tasks 📍 

- [x] Functional Spec @labkey-martyp 
- [x] Investigate TNPRC Requests @ankurjuneja @labkey-martyp 
- [x] Impl Plan
- [x] Add Tasks
- [x] Procedure Order Dataset
- [x] Procedure Dataset Updates
- [x] Procedure Order Form Section
- [x] Add to Clinical Forms
- [x] Procedure Order Clinical History
- [x] Schedule Query
- [x] Auto Load Procedures Form
- [x] Record Procedure, Link
- [x] Status Column
- [x] Bulk Record
- [x] Cancel Order
- [x] Reports
- [x] Code Review @labkey-bpatel
- [x] Code Review and User Feedback Updates
- [x] TC and Merge
